# Generated by Django 2.0.2 on 2020-11-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20201111_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='cname',
        ),
    ]
