# Generated by Django 2.0.2 on 2020-11-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201109_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_normal_user',
        ),
    ]
