# Generated by Django 2.0.2 on 2020-11-12 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201112_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mobile',
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(default=2, max_length=60, validators=[django.core.validators.RegexValidator(regex='^(91)\\d{10}$')]),
            preserve_default=False,
        ),
    ]
