# Generated by Django 2.0.2 on 2020-11-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_user_is_normal_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_administrator',
            new_name='is_admin',
        ),
    ]
