# Generated by Django 2.0.2 on 2020-11-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201112_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phone',
            new_name='mobile',
        ),
    ]
