# Generated by Django 2.0.2 on 2020-11-24 11:48

import django.core.validators
from django.db import migrations, models
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201124_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(max_length=250, validators=[myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='company',
            name='c_name',
            field=models.CharField(max_length=250, validators=[myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.CharField(max_length=60, validators=[django.core.validators.RegexValidator(regex='^(91)\\d{10}$'), myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=250, validators=[myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(), myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6, validators=[myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='user',
            name='hobby',
            field=models.CharField(max_length=250, validators=[myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=250, validators=[myapp.models.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=250, unique=True, validators=[myapp.models.validate_not_empty]),
        ),
    ]
